export const SPECIALTIES = {
    todas: {
        name: "Todas",
        icon: "fa-layer-group",
        bgColor: "bg-gray-800",
        lightBg: "bg-gray-100",
        textColor: "text-gray-800",
        borderColor: "border-gray-300",
        metricColor: "bg-gray-100",
    },
    fonoaudiologia: {
        name: "Fono",
        icon: "fa-ear-listen",
        bgColor: "bg-teal-600",
        lightBg: "bg-teal-100",
        textColor: "text-teal-800",
        borderColor: "border-teal-300",
        metricColor: "bg-teal-100",
    },
    psicologia: {
        name: "Psico",
        icon: "fa-brain",
        bgColor: "bg-violet-600",
        lightBg: "bg-violet-100",
        textColor: "text-violet-800",
        borderColor: "border-violet-300",
        metricColor: "bg-violet-100",
    },
    psicomotricidade: {
        name: "Psicomotricidade",
        icon: "fa-child-reaching",
        bgColor: "bg-lime-600",
        lightBg: "bg-lime-100",
        textColor: "text-lime-800",
        borderColor: "border-lime-300",
        metricColor: "bg-lime-100",
    },
    psicopedagogia: {
        name: "Psicopedagogia",
        icon: "fa-book-open",
        bgColor: "bg-cyan-600",
        lightBg: "bg-cyan-100",
        textColor: "text-cyan-800",
        borderColor: "border-cyan-300",
        metricColor: "bg-cyan-100",
    },
    terapia_ocupacional: {
        name: "Ter. Ocup",
        icon: "fa-hands-holding-child",
        bgColor: "bg-amber-600",
        lightBg: "bg-amber-100",
        textColor: "text-amber-800",
        borderColor: "border-amber-300",
        metricColor: "bg-amber-100",
    },
    fisioterapia: {
        name: "Fisio",
        icon: "fa-person-walking",
        bgColor: "bg-sky-600",
        lightBg: "bg-sky-100",
        textColor: "text-sky-800",
        borderColor: "border-sky-300",
        metricColor: "bg-sky-100",
    },
    tongue_tie_test: {
        name: "Teste da Linguinha",
        icon: "fa-face-smile",
        bgColor: "bg-fuchsia-600",
        lightBg: "bg-fuchsia-100",
        textColor: "text-fuchsia-800",
        borderColor: "border-fuchsia-300",
        metricColor: "bg-fuchsia-100",
    },
    neuropsych_evaluation: {
        name: "Av. Neuropsico",
        icon: "fa-brain",
        bgColor: "bg-rose-600",
        lightBg: "bg-rose-100",
        textColor: "text-rose-800",
        borderColor: "border-rose-300",
        metricColor: "bg-rose-100",
    },
    pediatria: {
        name: "Pediatria",
        icon: "fa-baby",
        bgColor: "bg-indigo-600",
        lightBg: "bg-indigo-100",
        textColor: "text-indigo-800",
        borderColor: "border-indigo-300",
        metricColor: "bg-indigo-100",
    },
    neuroped: {
        name: "Neuropediatria",
        icon: "fa-user-doctor",
        bgColor: "bg-red-600",
        lightBg: "bg-red-100",
        textColor: "text-red-800",
        borderColor: "border-red-300",
        metricColor: "bg-red-100",
    },
    musicoterapia: {
        name: "Musicoterapia",
        icon: "fa-music",
        bgColor: "bg-orange-600",
        lightBg: "bg-orange-100",
        textColor: "text-orange-800",
        borderColor: "border-orange-300",
        metricColor: "bg-orange-100",
    },
};


export const SPECIALTY_KEY_BY_LABEL = {
    Todas: "todas",
    Fonoaudiologia: "fonoaudiologia",
    Fono: "fonoaudiologia",
    Psicologia: "psicologia",
    Psico: "psicologia",
    Psicomotricidade: "psicomotricidade",
    Psicopedagogia: "psicopedagogia",
    "Terapia Ocupacional": "terapia_ocupacional",
    "Ter. Ocup": "terapia_ocupacional",
    Fisioterapia: "fisioterapia",
    Fisio: "fisioterapia",
    "Teste da Linguinha": "tongue_tie_test",
    "Avaliação Neuropsicológica": "neuropsych_evaluation",
    "Av. Neuropsico": "neuropsych_evaluation",
    Pediatria: "pediatria",
    Neuropediatria: "neuroped",
    Musicoterapia: "musicoterapia",
};
