export const SPECIALTIES = {
    todas: {
        name: "Todas",
        icon: "fa-layer-group",
        bgColor: "bg-gray-700",
        lightBg: "bg-gray-50",
        textColor: "text-gray-700",
        borderColor: "border-gray-300",
        metricColor: "bg-gray-50",
    },
    fonoaudiologia: {
        name: "Fonoaudiologia",
        icon: "fa-ear-listen",
        bgColor: "bg-teal-600",
        lightBg: "bg-teal-50",
        textColor: "text-teal-700",
        borderColor: "border-teal-300",
        metricColor: "bg-teal-50",
    },
    psicologia: {
        name: "Psicologia",
        icon: "fa-brain",
        bgColor: "bg-violet-600",
        lightBg: "bg-violet-50",
        textColor: "text-violet-700",
        borderColor: "border-violet-300",
        metricColor: "bg-violet-50",
    },
    psicomotricidade: {
        name: "Psicomotricidade",
        icon: "fa-child-reaching",
        bgColor: "bg-emerald-600",
        lightBg: "bg-emerald-50",
        textColor: "text-emerald-700",
        borderColor: "border-emerald-300",
        metricColor: "bg-emerald-50",
    },
    psicopedagogia: {
        name: "Psicopedagogia",
        icon: "fa-book-open",
        bgColor: "bg-indigo-600",
        lightBg: "bg-indigo-50",
        textColor: "text-indigo-700",
        borderColor: "border-indigo-300",
        metricColor: "bg-indigo-50",
    },
    terapia_ocupacional: {
        name: "Terapia Ocupacional",
        icon: "fa-hands-holding-child",
        bgColor: "bg-amber-600",
        lightBg: "bg-amber-50",
        textColor: "text-amber-700",
        borderColor: "border-amber-300",
        metricColor: "bg-amber-50",
    },
    fisioterapia: {
        name: "Fisioterapia",
        icon: "fa-person-walking",
        bgColor: "bg-blue-600",
        lightBg: "bg-blue-50",
        textColor: "text-blue-700",
        borderColor: "border-blue-300",
        metricColor: "bg-blue-50",
    },
};


export const SPECIALTY_KEY_BY_LABEL = {
    Todas: "todas",
    Fonoaudiologia: "fonoaudiologia",
    Psicologia: "psicologia",
    Psicomotricidade: "psicomotricidade",
    Psicopedagogia: "psicopedagogia",
    "Terapia Ocupacional": "terapia_ocupacional",
    Fisioterapia: "fisioterapia",
};
