export const SPECIALTIES = {
    todas: {
        name: "Todas",
        icon: "fa-layer-group",
        bgColor: "bg-gray-700",
        lightBg: "bg-gray-50",
        textColor: "text-gray-700",
        borderColor: "border-gray-300",
        metricColor: "bg-gray-50",
    },
    fonoaudiologia: {
        name: "Fonoaudiologia",
        icon: "fa-ear-listen",
        bgColor: "bg-teal-600",
        lightBg: "bg-teal-50",
        textColor: "text-teal-700",
        borderColor: "border-teal-300",
        metricColor: "bg-teal-50",
    },
    psicologia: {
        name: "Psicologia",
        icon: "fa-brain",
        bgColor: "bg-violet-600",
        lightBg: "bg-violet-50",
        textColor: "text-violet-700",
        borderColor: "border-violet-300",
        metricColor: "bg-violet-50",
    },
    psicomotricidade: {
        name: "Psicomotricidade",
        icon: "fa-child-reaching",
        bgColor: "bg-emerald-600",
        lightBg: "bg-emerald-50",
        textColor: "text-emerald-700",
        borderColor: "border-emerald-300",
        metricColor: "bg-emerald-50",
    },
    psicopedagogia: {
        name: "Psicopedagogia",
        icon: "fa-book-open",
        bgColor: "bg-indigo-600",
        lightBg: "bg-indigo-50",
        textColor: "text-indigo-700",
        borderColor: "border-indigo-300",
        metricColor: "bg-indigo-50",
    },
    terapia_ocupacional: {
        name: "Terapia Ocupacional",
        icon: "fa-hands-holding-child",
        bgColor: "bg-amber-600",
        lightBg: "bg-amber-50",
        textColor: "text-amber-700",
        borderColor: "border-amber-300",
        metricColor: "bg-amber-50",
    },
    fisioterapia: {
        name: "Fisioterapia",
        icon: "fa-person-walking",
        bgColor: "bg-blue-600",
        lightBg: "bg-blue-50",
        textColor: "text-blue-700",
        borderColor: "border-blue-300",
        metricColor: "bg-blue-50",
    },
    tongue_tie_test: {
        name: "Teste da Linguinha",
        icon: "fa-face-smile",
        bgColor: "bg-pink-600",
        lightBg: "bg-pink-50",
        textColor: "text-pink-700",
        borderColor: "border-pink-300",
        metricColor: "bg-pink-50",
    },
    neuropsych_evaluation: {
        name: "Avaliação Neuropsicológica",
        icon: "fa-brain",
        bgColor: "bg-purple-600",
        lightBg: "bg-purple-50",
        textColor: "text-purple-700",
        borderColor: "border-purple-300",
        metricColor: "bg-purple-50",
    },
    pediatria: {
        name: "Pediatria",
        icon: "fa-baby",
        bgColor: "bg-cyan-600",
        lightBg: "bg-cyan-50",
        textColor: "text-cyan-700",
        borderColor: "border-cyan-300",
        metricColor: "bg-cyan-50",
    },
    neuroped: {
        name: "Neuropediatria",
        icon: "fa-user-doctor",
        bgColor: "bg-rose-600",
        lightBg: "bg-rose-50",
        textColor: "text-rose-700",
        borderColor: "border-rose-300",
        metricColor: "bg-rose-50",
    },
    musicoterapia: {
        name: "Musicoterapia",
        icon: "fa-music",
        bgColor: "bg-orange-600",
        lightBg: "bg-orange-50",
        textColor: "text-orange-700",
        borderColor: "border-orange-300",
        metricColor: "bg-orange-50",
    },
};


export const SPECIALTY_KEY_BY_LABEL = {
    Todas: "todas",
    Fonoaudiologia: "fonoaudiologia",
    Psicologia: "psicologia",
    Psicomotricidade: "psicomotricidade",
    Psicopedagogia: "psicopedagogia",
    "Terapia Ocupacional": "terapia_ocupacional",
    Fisioterapia: "fisioterapia",
    "Teste da Linguinha": "tongue_tie_test",
    "Avaliação Neuropsicológica": "neuropsych_evaluation",
    Pediatria: "pediatria",
    Neuropediatria: "neuroped",
    Musicoterapia: "musicoterapia",
};
